// ===== Campus Bites Store Dashboard — Mock Data =====

export const storeConfig = {
    id: 's3',
    courtId: 'fc1',
    name: 'Pizza Planet',
    image: '🍕',
    cuisine: 'Italian & Pizza',
    description: 'Freshly baked pizzas, pastas, and sides — loved by every campus foodie!',
    rating: 4.7,
    totalReviews: 342,
    prepTime: '12-18 min',
    isOpen: true,
    ownerName: 'Rahul Sharma',
    ownerAvatar: '👨‍🍳',
    phone: '+91 98765 43210',
    upiId: 'pizzaplanet@upi',
    operatingHours: {
        monday: { open: '09:00', close: '22:00', isOpen: true },
        tuesday: { open: '09:00', close: '22:00', isOpen: true },
        wednesday: { open: '09:00', close: '22:00', isOpen: true },
        thursday: { open: '09:00', close: '22:00', isOpen: true },
        friday: { open: '09:00', close: '23:00', isOpen: true },
        saturday: { open: '10:00', close: '23:00', isOpen: true },
        sunday: { open: '10:00', close: '21:00', isOpen: false },
    },
};

export const dashboardMenuItems = [
    { id: 'm12', name: 'Margherita Pizza', category: 'Pizzas', price: 199, prepTime: 15, isVeg: true, image: '🍕', description: 'Classic mozzarella and basil', isAvailable: true },
    { id: 'm13', name: 'Pepperoni Pizza', category: 'Pizzas', price: 249, prepTime: 15, isVeg: false, image: '🍕', description: 'Loaded with spicy pepperoni', isAvailable: true },
    { id: 'm14', name: 'Garlic Bread', category: 'Sides', price: 99, prepTime: 8, isVeg: true, image: '🥖', description: 'Toasted with garlic butter', isAvailable: true },
    { id: 'm15', name: 'Pasta Alfredo', category: 'Pasta', price: 179, prepTime: 12, isVeg: true, image: '🍝', description: 'Creamy white sauce pasta', isAvailable: true },
    { id: 'm16', name: 'Cold Coffee', category: 'Beverages', price: 89, prepTime: 3, isVeg: true, image: '🧋', description: 'Chilled coffee with ice cream', isAvailable: true },
    { id: 'm101', name: 'BBQ Chicken Pizza', category: 'Pizzas', price: 279, prepTime: 18, isVeg: false, image: '🍕', description: 'Smoky BBQ chicken with onions', isAvailable: true },
    { id: 'm102', name: 'Paneer Tikka Pizza', category: 'Pizzas', price: 229, prepTime: 16, isVeg: true, image: '🍕', description: 'Tandoori paneer with capsicum', isAvailable: false },
    { id: 'm103', name: 'Cheese Fries', category: 'Sides', price: 119, prepTime: 8, isVeg: true, image: '🍟', description: 'Crispy fries loaded with cheese', isAvailable: true },
    { id: 'm104', name: 'Penne Arrabiata', category: 'Pasta', price: 169, prepTime: 12, isVeg: true, image: '🍝', description: 'Spicy tomato pasta', isAvailable: true },
    { id: 'm105', name: 'Mojito', category: 'Beverages', price: 79, prepTime: 4, isVeg: true, image: '🍹', description: 'Refreshing mint & lime cooler', isAvailable: true },
    { id: 'm106', name: 'Brownie Sundae', category: 'Desserts', price: 149, prepTime: 5, isVeg: true, image: '🍫', description: 'Warm brownie with vanilla ice cream', isAvailable: true },
    { id: 'm107', name: 'Tiramisu', category: 'Desserts', price: 179, prepTime: 3, isVeg: true, image: '🍰', description: 'Classic Italian coffee dessert', isAvailable: false },
];

// Generate a 4-digit OTP
const generateOTP = () => String(Math.floor(1000 + Math.random() * 9000));

// Generate timestamps relative to now
const ago = (minutes) => new Date(Date.now() - minutes * 60000).toISOString();
const fromNow = (minutes) => new Date(Date.now() + minutes * 60000).toISOString();

export const mockOrders = [
    // New orders (waiting for accept/reject)
    {
        id: 'ORD-A1B2C',
        customerName: 'Ananya K.',
        items: [
            { name: 'Margherita Pizza', qty: 2, price: 199 },
            { name: 'Garlic Bread', qty: 1, price: 99 },
        ],
        total: 497,
        status: 'new',
        paymentMethod: 'upi',
        otp: generateOTP(),
        placedAt: ago(2),
        estimatedReady: null,
    },
    {
        id: 'ORD-D3E4F',
        customerName: 'Vikram S.',
        items: [
            { name: 'BBQ Chicken Pizza', qty: 1, price: 279 },
            { name: 'Cold Coffee', qty: 2, price: 89 },
        ],
        total: 457,
        status: 'new',
        paymentMethod: 'cash',
        otp: generateOTP(),
        placedAt: ago(1),
        estimatedReady: null,
    },
    // Accepted / Preparing
    {
        id: 'ORD-G5H6I',
        customerName: 'Priya M.',
        items: [
            { name: 'Pasta Alfredo', qty: 1, price: 179 },
            { name: 'Mojito', qty: 1, price: 79 },
        ],
        total: 258,
        status: 'preparing',
        paymentMethod: 'upi',
        otp: generateOTP(),
        placedAt: ago(8),
        estimatedReady: fromNow(5),
    },
    {
        id: 'ORD-J7K8L',
        customerName: 'Rohan P.',
        items: [
            { name: 'Pepperoni Pizza', qty: 1, price: 249 },
            { name: 'Cheese Fries', qty: 1, price: 119 },
            { name: 'Cold Coffee', qty: 1, price: 89 },
        ],
        total: 457,
        status: 'preparing',
        paymentMethod: 'card',
        otp: generateOTP(),
        placedAt: ago(12),
        estimatedReady: fromNow(3),
    },
    // Ready for pickup
    {
        id: 'ORD-M9N0O',
        customerName: 'Sneha R.',
        items: [
            { name: 'Paneer Tikka Pizza', qty: 1, price: 229 },
            { name: 'Brownie Sundae', qty: 1, price: 149 },
        ],
        total: 378,
        status: 'ready',
        paymentMethod: 'upi',
        otp: generateOTP(),
        placedAt: ago(20),
        estimatedReady: ago(2),
    },
    // Completed
    {
        id: 'ORD-P1Q2R',
        customerName: 'Amit D.',
        items: [{ name: 'Margherita Pizza', qty: 1, price: 199 }],
        total: 199,
        status: 'completed',
        paymentMethod: 'upi',
        otp: '4829',
        placedAt: ago(45),
        estimatedReady: ago(30),
        completedAt: ago(28),
    },
    {
        id: 'ORD-S3T4U',
        customerName: 'Kavya N.',
        items: [
            { name: 'Pasta Alfredo', qty: 2, price: 179 },
            { name: 'Garlic Bread', qty: 2, price: 99 },
        ],
        total: 556,
        status: 'completed',
        paymentMethod: 'cash',
        otp: '7291',
        placedAt: ago(90),
        estimatedReady: ago(75),
        completedAt: ago(72),
    },
    {
        id: 'ORD-V5W6X',
        customerName: 'Arjun T.',
        items: [
            { name: 'BBQ Chicken Pizza', qty: 1, price: 279 },
            { name: 'Penne Arrabiata', qty: 1, price: 169 },
        ],
        total: 448,
        status: 'completed',
        paymentMethod: 'upi',
        otp: '3156',
        placedAt: ago(120),
        estimatedReady: ago(105),
        completedAt: ago(100),
    },
    {
        id: 'ORD-Y7Z8A',
        customerName: 'Meera J.',
        items: [{ name: 'Cold Coffee', qty: 3, price: 89 }],
        total: 267,
        status: 'completed',
        paymentMethod: 'upi',
        otp: '8462',
        placedAt: ago(180),
        estimatedReady: ago(175),
        completedAt: ago(173),
    },
    // Rejected
    {
        id: 'ORD-B9C0D',
        customerName: 'Tarun G.',
        items: [{ name: 'Tiramisu', qty: 2, price: 179 }],
        total: 358,
        status: 'rejected',
        paymentMethod: 'cash',
        otp: '5037',
        placedAt: ago(60),
        rejectedReason: 'Item out of stock',
    },
];

export const mockPayments = [
    { id: 'PAY-001', orderId: 'ORD-P1Q2R', amount: 199, method: 'upi', status: 'settled', date: ago(28) },
    { id: 'PAY-002', orderId: 'ORD-S3T4U', amount: 556, method: 'cash', status: 'settled', date: ago(72) },
    { id: 'PAY-003', orderId: 'ORD-V5W6X', amount: 448, method: 'upi', status: 'settled', date: ago(100) },
    { id: 'PAY-004', orderId: 'ORD-Y7Z8A', amount: 267, method: 'upi', status: 'settled', date: ago(173) },
    { id: 'PAY-005', orderId: 'ORD-M9N0O', amount: 378, method: 'upi', status: 'pending', date: ago(20) },
    { id: 'PAY-006', orderId: 'ORD-G5H6I', amount: 258, method: 'upi', status: 'pending', date: ago(8) },
    { id: 'PAY-007', orderId: 'ORD-J7K8L', amount: 457, method: 'card', status: 'pending', date: ago(12) },
    { id: 'PAY-008', orderId: 'ORD-A1B2C', amount: 497, method: 'upi', status: 'pending', date: ago(2) },
    { id: 'PAY-009', orderId: 'ORD-D3E4F', amount: 457, method: 'cash', status: 'pending', date: ago(1) },
];

export const mockAnalytics = {
    revenueByDay: [
        { day: 'Mon', revenue: 4200 },
        { day: 'Tue', revenue: 5100 },
        { day: 'Wed', revenue: 3800 },
        { day: 'Thu', revenue: 6200 },
        { day: 'Fri', revenue: 7500 },
        { day: 'Sat', revenue: 8100 },
        { day: 'Sun', revenue: 3200 },
    ],
    ordersByDay: [
        { day: 'Mon', orders: 28 },
        { day: 'Tue', orders: 34 },
        { day: 'Wed', orders: 25 },
        { day: 'Thu', orders: 41 },
        { day: 'Fri', orders: 52 },
        { day: 'Sat', orders: 55 },
        { day: 'Sun', orders: 22 },
    ],
    popularItems: [
        { name: 'Margherita Pizza', orders: 87, revenue: 17313 },
        { name: 'Pepperoni Pizza', orders: 62, revenue: 15438 },
        { name: 'Pasta Alfredo', orders: 51, revenue: 9129 },
        { name: 'Garlic Bread', orders: 48, revenue: 4752 },
        { name: 'Cold Coffee', orders: 45, revenue: 4005 },
        { name: 'BBQ Chicken Pizza', orders: 38, revenue: 10602 },
    ],
    peakHours: [
        { hour: '9AM', orders: 5 },
        { hour: '10AM', orders: 8 },
        { hour: '11AM', orders: 12 },
        { hour: '12PM', orders: 28 },
        { hour: '1PM', orders: 35 },
        { hour: '2PM', orders: 22 },
        { hour: '3PM', orders: 15 },
        { hour: '4PM', orders: 18 },
        { hour: '5PM', orders: 25 },
        { hour: '6PM', orders: 32 },
        { hour: '7PM', orders: 38 },
        { hour: '8PM', orders: 30 },
        { hour: '9PM', orders: 20 },
        { hour: '10PM', orders: 10 },
    ],
    summary: {
        todayRevenue: 3817,
        todayOrders: 18,
        avgPrepTime: 13,
        rating: 4.7,
        weekRevenue: 38100,
        weekOrders: 257,
        monthRevenue: 152400,
        monthOrders: 1028,
        newCustomersPercent: 35,
        returningCustomersPercent: 65,
    },
};

// ===== Address Book =====

export const mockAddressBook = [
    {
        id: 'addr-1',
        label: 'Hostel Room',
        name: 'Ananya Kapoor',
        phone: '+91 98765 43210',
        addressLine1: 'Room 302, Boys Hostel Block-A',
        addressLine2: 'University Campus, Main Gate Road',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411007',
        landmark: 'Near Campus Library',
        type: 'hostel',
        isDefault: true,
        lat: 18.5204,
        lng: 73.8567,
    },
    {
        id: 'addr-2',
        label: 'Home',
        name: 'Ananya Kapoor',
        phone: '+91 98765 43210',
        addressLine1: '42, Sunrise Apartments, 3rd Floor',
        addressLine2: 'MG Road, Koregaon Park',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411001',
        landmark: 'Opposite City Mall',
        type: 'home',
        isDefault: false,
        lat: 18.5362,
        lng: 73.8938,
    },
    {
        id: 'addr-3',
        label: 'Friend\'s Place',
        name: 'Vikram Sharma',
        phone: '+91 91234 56789',
        addressLine1: 'Flat 12B, Green Valley Residency',
        addressLine2: 'Baner Road, Near Orchid School',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411045',
        landmark: 'Behind D-Mart Baner',
        type: 'apartment',
        isDefault: false,
        lat: 18.5590,
        lng: 73.7868,
    },
    {
        id: 'addr-4',
        label: 'PG Accommodation',
        name: 'Priya Mehta',
        phone: '+91 87654 32109',
        addressLine1: 'Shree Sai PG, Room 14',
        addressLine2: 'Lane 5, Aundh IT Park Road',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411027',
        landmark: 'Next to Reliance Fresh',
        type: 'pg',
        isDefault: false,
        lat: 18.5580,
        lng: 73.8077,
    },
    {
        id: 'addr-5',
        label: 'Campus Gate',
        name: 'Rohan Patil',
        phone: '+91 99887 65432',
        addressLine1: 'Main Entrance Gate',
        addressLine2: 'University of Pune Campus',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411007',
        landmark: 'Security Cabin, Gate No. 1',
        type: 'campus',
        isDefault: false,
        lat: 18.5196,
        lng: 73.8553,
    },
    {
        id: 'addr-6',
        label: 'Department Building',
        name: 'Sneha Reddy',
        phone: '+91 90909 12345',
        addressLine1: 'Computer Science Dept, 2nd Floor',
        addressLine2: 'Academic Block-C, University Campus',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411007',
        landmark: 'Near Admin Building',
        type: 'department',
        isDefault: false,
        lat: 18.5210,
        lng: 73.8560,
    },
];

// ===== SUPER ADMIN — Multi-Store Data =====

export const PLATFORM_FEE_PER_ORDER = 2; // ₹2 per completed order

export const allStores = [
    {
        id: 's1', courtId: 'fc1', name: 'Dosa Express', image: '🥘', cuisine: 'South Indian',
        ownerName: 'Priya Nair', ownerAvatar: '👩‍🍳', phone: '+91 99887 11001', upiId: 'dosaexpress@upi',
        rating: 4.5, totalReviews: 287, isOpen: true,
        todayOrders: 24, todayRevenue: 4560, weekOrders: 168, weekRevenue: 31920, monthOrders: 720, monthRevenue: 136800,
    },
    {
        id: 's2', courtId: 'fc1', name: 'Chai Corner', image: '☕', cuisine: 'Beverages & Snacks',
        ownerName: 'Amit Joshi', ownerAvatar: '🧔', phone: '+91 99887 22002', upiId: 'chaicorner@upi',
        rating: 4.3, totalReviews: 198, isOpen: true,
        todayOrders: 32, todayRevenue: 2880, weekOrders: 224, weekRevenue: 20160, monthOrders: 960, monthRevenue: 86400,
    },
    {
        id: 's3', courtId: 'fc1', name: 'Pizza Planet', image: '🍕', cuisine: 'Italian & Pizza',
        ownerName: 'Rahul Sharma', ownerAvatar: '👨‍🍳', phone: '+91 98765 43210', upiId: 'pizzaplanet@upi',
        rating: 4.7, totalReviews: 342, isOpen: true,
        todayOrders: 18, todayRevenue: 3817, weekOrders: 257, weekRevenue: 38100, monthOrders: 1028, monthRevenue: 152400,
    },
    {
        id: 's4', courtId: 'fc2', name: 'Burger Barn', image: '🍔', cuisine: 'American Fast Food',
        ownerName: 'Karan Singh', ownerAvatar: '👨‍🍳', phone: '+91 99887 44004', upiId: 'burgerbarn@upi',
        rating: 4.6, totalReviews: 412, isOpen: false,
        todayOrders: 0, todayRevenue: 0, weekOrders: 195, weekRevenue: 35100, monthOrders: 845, monthRevenue: 152100,
    },
    {
        id: 's5', courtId: 'fc2', name: 'Wok This Way', image: '🥡', cuisine: 'Chinese & Asian',
        ownerName: 'Meera Gupta', ownerAvatar: '👩‍🍳', phone: '+91 99887 55005', upiId: 'wokthisway@upi',
        rating: 4.4, totalReviews: 256, isOpen: true,
        todayOrders: 21, todayRevenue: 3990, weekOrders: 147, weekRevenue: 27930, monthOrders: 630, monthRevenue: 119700,
    },
];

export const allStoreOrders = [
    // Dosa Express
    { id: 'ORD-DE001', storeId: 's1', storeName: 'Dosa Express', customerName: 'Ravi K.', items: [{ name: 'Masala Dosa', qty: 2, price: 120 }], total: 240, status: 'completed', paymentMethod: 'upi', placedAt: ago(30), completedAt: ago(15) },
    { id: 'ORD-DE002', storeId: 's1', storeName: 'Dosa Express', customerName: 'Sita L.', items: [{ name: 'Idli Sambar', qty: 3, price: 80 }], total: 240, status: 'completed', paymentMethod: 'cash', placedAt: ago(60), completedAt: ago(45) },
    { id: 'ORD-DE003', storeId: 's1', storeName: 'Dosa Express', customerName: 'Neha P.', items: [{ name: 'Rava Dosa', qty: 1, price: 140 }, { name: 'Filter Coffee', qty: 2, price: 40 }], total: 220, status: 'preparing', paymentMethod: 'upi', placedAt: ago(5) },
    // Chai Corner
    { id: 'ORD-CC001', storeId: 's2', storeName: 'Chai Corner', customerName: 'Aditya R.', items: [{ name: 'Cutting Chai', qty: 4, price: 20 }, { name: 'Samosa', qty: 4, price: 25 }], total: 180, status: 'completed', paymentMethod: 'cash', placedAt: ago(20), completedAt: ago(10) },
    { id: 'ORD-CC002', storeId: 's2', storeName: 'Chai Corner', customerName: 'Pooja M.', items: [{ name: 'Masala Chai', qty: 2, price: 30 }], total: 60, status: 'new', paymentMethod: 'upi', placedAt: ago(2) },
    // Pizza Planet
    { id: 'ORD-PP001', storeId: 's3', storeName: 'Pizza Planet', customerName: 'Ananya K.', items: [{ name: 'Margherita Pizza', qty: 2, price: 199 }, { name: 'Garlic Bread', qty: 1, price: 99 }], total: 497, status: 'new', paymentMethod: 'upi', placedAt: ago(2) },
    { id: 'ORD-PP002', storeId: 's3', storeName: 'Pizza Planet', customerName: 'Vikram S.', items: [{ name: 'BBQ Chicken Pizza', qty: 1, price: 279 }], total: 279, status: 'completed', paymentMethod: 'card', placedAt: ago(50), completedAt: ago(35) },
    { id: 'ORD-PP003', storeId: 's3', storeName: 'Pizza Planet', customerName: 'Priya M.', items: [{ name: 'Pasta Alfredo', qty: 1, price: 179 }], total: 179, status: 'completed', paymentMethod: 'upi', placedAt: ago(90), completedAt: ago(75) },
    // Burger Barn
    { id: 'ORD-BB001', storeId: 's4', storeName: 'Burger Barn', customerName: 'Rohit D.', items: [{ name: 'Classic Burger', qty: 2, price: 149 }, { name: 'Fries', qty: 1, price: 89 }], total: 387, status: 'completed', paymentMethod: 'upi', placedAt: ago(200), completedAt: ago(180) },
    { id: 'ORD-BB002', storeId: 's4', storeName: 'Burger Barn', customerName: 'Anita S.', items: [{ name: 'Chicken Burger', qty: 1, price: 179 }], total: 179, status: 'completed', paymentMethod: 'cash', placedAt: ago(240), completedAt: ago(220) },
    // Wok This Way
    { id: 'ORD-WT001', storeId: 's5', storeName: 'Wok This Way', customerName: 'Deepak V.', items: [{ name: 'Fried Rice', qty: 1, price: 159 }, { name: 'Manchurian', qty: 1, price: 139 }], total: 298, status: 'completed', paymentMethod: 'upi', placedAt: ago(40), completedAt: ago(25) },
    { id: 'ORD-WT002', storeId: 's5', storeName: 'Wok This Way', customerName: 'Nisha K.', items: [{ name: 'Hakka Noodles', qty: 2, price: 149 }], total: 298, status: 'preparing', paymentMethod: 'card', placedAt: ago(8) },
    { id: 'ORD-WT003', storeId: 's5', storeName: 'Wok This Way', customerName: 'Raj T.', items: [{ name: 'Spring Roll', qty: 3, price: 99 }], total: 297, status: 'completed', paymentMethod: 'upi', placedAt: ago(120), completedAt: ago(105) },
];

export const adminAnalytics = {
    platformFeesByDay: [
        { day: 'Mon', fees: 56, orders: 28 },
        { day: 'Tue', fees: 68, orders: 34 },
        { day: 'Wed', fees: 50, orders: 25 },
        { day: 'Thu', fees: 82, orders: 41 },
        { day: 'Fri', fees: 104, orders: 52 },
        { day: 'Sat', fees: 110, orders: 55 },
        { day: 'Sun', fees: 44, orders: 22 },
    ],
    storeFees: [
        { storeId: 's1', storeName: 'Dosa Express', completedOrders: 720, totalFees: 1440, settled: 1200, pending: 240 },
        { storeId: 's2', storeName: 'Chai Corner', completedOrders: 960, totalFees: 1920, settled: 1800, pending: 120 },
        { storeId: 's3', storeName: 'Pizza Planet', completedOrders: 1028, totalFees: 2056, settled: 1900, pending: 156 },
        { storeId: 's4', storeName: 'Burger Barn', completedOrders: 845, totalFees: 1690, settled: 1690, pending: 0 },
        { storeId: 's5', storeName: 'Wok This Way', completedOrders: 630, totalFees: 1260, settled: 1100, pending: 160 },
    ],
    summary: {
        totalStores: 5,
        activeStores: 4,
        totalOrdersToday: 95,
        totalRevenueToday: 15247,
        totalFeesToday: 190,
        totalFeesWeek: 514,
        totalFeesMonth: 8366,
        totalFeesAllTime: 8366,
    },
};
